import React from 'react';
import './AboutUs.css'

const AboutUs = () => {
    return (
        <div>
            <div >
                <h1>Privacy Policy</h1>
                <p className='AboutUs'>
                    We, 10MS Limited, incorporated under the Bangladeshi Companies Act (Act XVIII), of 1994 (hereinafter referred to as “Company”), with the incorporation number C162578 / 2020, is committed to safeguarding your privacy in relation to the protection of your personal information. To guarantee our ability to access your services, we may obtain and sometimes share your information. In order to further safeguard your privacy, we give this notice that details our information practices and the options you have when it comes to the collection and use of your information.
                    In order to ensure that all users of the website, https://10minuteschool.com/ (henceforth "the website") and the "10 Minute School application" (henceforth "the Application") are aware of the privacy policy that governs the use of the website and the application, we advise you to read the Privacy Policy and accept the terms and conditions contained herein by logging into the website or application. You must agree to our Privacy Policy, which covers the collecting and use of your personal information, or you are not permitted to use the Website or App. You can contact our Customer Support if you have any questions or complaints about this privacy policy at support@10minuteschool.com.
                </p>
                <h2>1. DEFINITIONS</h2>
                <p className='AboutUs'>“We”, “Our”, and “Us” -  Refers to the creators of this privacy policy.
                    “You”, “Your”, “Yourself” and “User” -  Refers to natural and legal individuals who use the Website.
                    “Website” -  Refers to the official website of 10 Minute School created by 10MS Limited
                    “App” -  Refers to 10 Minute School app created by 10MS Limited
                    “Personal Information” -  Refers to any personally identifiable information that We may collect from You.
                    “Third Parties” -  Refers to any website, company or individual apart from the user and the creator of the Website.
                </p>
                <h2>2. OVERVIEW</h2>
                <p className='AboutUs'>We take the responsibility to respect your private information online. We further acknowledge the need to preserve and handle the information you share with us that is identifiable personally ("personal information"). Information which we regard as personal about you includes but is not confined to your name, address, e-mail address, phone number or other contact details. You must provide the following information, but it is not limited to: phone number; bank information; date of birth; class, school, subjects and syllabus; e-mail address in order to buy a product from our website or application. This Privacy Policy also applies to data collected from users who are not recorded as members, including but not limited to surfing behavior, pages viewed etc. In addition, the Website and App requests permits to link your 10 Minute School Account to your Social Account, and if you have provided permission to link the Accounts, the information shall be gathered straight from your social media account. </p>
                <h2>3. User Provided Information</h2>
                <p className='AboutUs'>The Application/Website/Services/Products obtains the information you provide when you download and register for the Application or Services or products. When you register with us, you generally provide (a) your name, age, e-mail address, address, phone number, password and educational interests of your ward; (b) transaction-related information such as when making purchases, responding to offers or downloading or using applications from us; (c) information you provide us when you contact us for help; (d) information you enter into our system when using the Application/Services/Products, such as while asking doubts, participating in discussions and taking tests. This information shall be regarded as ‘Personal Information’. In order to give you the service, important information, the required notifications and marketing promotions, we can use the Information from time to time. We will ask you if we need additional information that will identify you personally (personal information). We will not differentiate between those who use the device to access the request, site or services or products, provided that the credentials match your login/access credentials. It is essential that you have logged into it using your own credentials to make full use of the app/website/services/products and to enable your information to be accurately captured in the application/website/services/products.</p>
                <h2>4. Automatically Collected Information</h2>
                <p className='AboutUs'>In addition, the app/products/devices can automatically collect certain data, including, but not limited to, the mobile device types that you use, your mobile device unique device ID, your mobile operating device IP address, your mobile browser type and the use of the application/services/products information. We collect other relevant information according to the authorisations you give as is the case for most mobile applications. For payment of products and services, we use an outside credit card processing and payment gateway company. For any other purpose, these companies do not retain, share, store or use personal information.</p>
                <h2>5. HOW INFORMATION IS COLLECTED</h2>
                <p className='AboutUs'>We will determine the purpose of collecting the information before or when personal information is collected. Unless we have the consent or legal requirements of the appropriate personnel, we only collect and use personal data for the purposes specified by us and for other compatible purposes. For these purposes, we will only retain personal information for as long as is necessary. With the knowledge or consent of the appropriate personnel, we collect personal information in a lawful and fair manner as appropriate. Personal data shall be appropriate to the purposes for which it is used and shall, to the extent needed for those purposes, be accurate, complete and updated</p>
                <h2>6. COOKIES</h2>
                <p className='AboutUs'>
                    On certain pages of our website and applications, we use data collection devices such as "cookies." "Cookies" are small files on your hard disk that help us to deliver customized services. We also offer certain functionalities that can be used only by using cookies. Cookies can also assist us in providing your interests-oriented information. Cookies may be used to identify users that have been registered or logged in. Through your visit to this web page, third party providers may use cookies to serve ads, including Google.com ("Google"). You can visit the third-party website and choose not to use cookies for interest-based advertisements if a third party provides such options. By visiting "Add Settings," you can opt out for the receipt of DoubleClick cookies for Google and its partners. (Alternatively, by visiting aboutads.info), you can instruct users to opt out of the use of cookies by third party providers for interessional advertising). You can opt out here: https://tools.google.com/dlpage/gaoptout/ by downloading and installing the optout plugin for Google Analytics.
                </p>
                <h2>7. EXTERNAL LINKS ON WEBSITE</h2>
                <p className='AboutUs'>Hyperlinks to other websites, content or resources may be included on this Website. No website or resources supplied by companies or individuals other than ourselves are under our control. You recognize and agree that we cannot be liable for the access to any external website, resource or other material on or off such external websites or resources and do not endorse any such website or resource or other material. You acknowledge and agree that we are not responsible for any loss or damage caused by or in connection with the availability of such external websites or resources. Those providers of third-party services and websites may have their own privacy policy, which may affect the storage and retention of your personal data. We encourage you to review the website's privacy policy for protecting your personal information when visiting a third-party website. When you visit this website, we use third-party advertising companies.</p>
                <h2>8. OUR USE OF YOUR INFORMATION </h2>
                <p className='AboutUs'>Your contact details will be used as necessary to contact you. We diagnose problems with our servers by using your IP address and manage our website and applications. You can also identify and gather wide demographic information with IP addresses. Finally, with your IP address, we can help protect you against partnerships and fraud. With the availability of new technology, we will improve security. You will send us information about you, if we recover or merge in another company. In this case, before you transfer the information and receive different privacy policies, you will be notified via e-mail or by putting prominent notices on the site. We may disclose your personal information to the third party in order to comply with the court directives and similar law treatments, or to think that it needs the necessary sincerity to comply with the law and avoid impending physical damage or loss of money. Alternatively, investigate or take measures in connection with illegal actions, suspected fraud or violation of the terms and conditions of use. In accordance with our copyright policy, in conformity with our copyright policy, we may disclose personally identifiable information. You can disclose your name, address, country, telephone number, email address and name of your business. </p>
                <h2>9. CONFIDENTIALITY</h2>
                <p className='AboutUs'>You further acknowledge that this website may contain data that are confidential to us, and that without our prior written consent you may not disclose this information. Your information will not be disclosed to any third parties if required to do so by law by the appropriate authorities. Your information is considered confidential. No third party will be sold, shared or rented with us, nor will we send unwanted email via your email address. The emails we send relate only to services and products which we have agreed upon.</p>
                <h2>10. OUR DISCLOSURE OF YOUR INFORMATION</h2>
                <p className='AboutUs'>Due to the existing regulatory environment, we cannot guarantee that no other way of disclosing your personal communications and other information is described otherwise in this Privacy Policy. We may be forced to disclose information to the government, law enforcement agencies or third parties by way of an example (without limiting or forgoing). Under certain circumstances, third parties may unlawfully intercept or access transmissions or private communications, or members may abuse or misuse your information that they collect from our Website. We therefore do not, and should not expect, that your personal information, identifiable or private communication will always remain private even though we apply industry standard practices to protect your privacy. We don't sell or rent information about you to any third party as a matter of policy. The following describes, however, certain ways in which you can disclose your personal information: Providers of external services: You can use our websites with a variety of services offered by external providers. When you use these optional services and they need to collect data from you, their privacy policy will apply. Other entities in the corporate world: Your personal information is shared with our parent and/or subsidiaries that will help you with your online needs and related services, which are available around the world. These details will be provided to you exclusively to improve your browsing experience and to provide our services. They will treat your information like they do that of their other members, as long as they have access to it. The company and/or its subsidiaries, or all of them, may be acquired or merged with another business entity. We would share some or all of your personal information if the combination of services you ordered were not available on our own servers. In the event of such an occurrence, you will be notified (to the extent that it occurs). We work with various other agencies, including law enforcement, to ensure the enforcement of various laws, including: intellectual property, fraud, and other property rights. You authorize us to share any personal information with law enforcement and government officials in case of an investigation into fraud, intellectual, or other illegal activities that may expose us or you to legal liability. </p>
            </div>


        </div>
    );
};

export default AboutUs; <h1>this is export defa ul</h1>